<article>

	<table>
		<caption>
			Convert Font Sizes from Pixels to Ems or Percentages
		</caption>
	
		<thead>
			<tr>
				<th>PIXELS</th>
				<th>EMS</th>
				<th>PERCENTAGES</th>
			</tr>
		</thead>
	
		<tfoot>
			<tr>
				<td colspan="3">Conversions provided by <a href="http://pxtoem.com/">PXtoEM.com</a></td>
			</tr>
		</tfoot>
	
		<tbody>
			<tr>
				<td>16px</td>
				<td>1em</td>
				<td>100%</td>
			</tr>
	
			<tr>
				<td>17px</td>
				<td>1.063em</td>
				<td>106.3%</td>
			</tr>
	
			<tr>
				<td>18px</td>
				<td>1.125em</td>
				<td>112.5%</td>
			</tr>
	
			<tr>
				<td>19px</td>
				<td>1.188em</td>
				<td>118.8%</td>
			</tr>
		</tbody>
	</table>

</article>